# ===============================
# Remote Docker MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://db:3306/course_monitor_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf-8&createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# ===============================
# Production JPA Settings
# ===============================
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# ===============================
# Production RabbitMQ
# ===============================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# ===============================
# Production Redis
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
